settings:
  enabled-by-default: false
  prefix: "§x§E§D§D§1§4§FL§x§E§F§C§B§5§6o§x§F§0§C§5§5§Cu§x§F§2§C§0§6§3n§x§F§4§B§A§6§Ag§x§F§5§B§4§7§1e§x§F§7§A§E§7§7F§x§F§8§A§8§7§Ei§x§F§A§A§2§8§5l§x§F§C§9§D§8§Ct§x§F§D§9§7§9§2e§x§F§F§9§1§9§9r &8&l|"
  
  caps:
    enabled: true
    threshold: 0.7  # Процент заглавных букв для срабатывания (0.7 = 70%)
    min-length: 5   # Минимальная длина сообщения для проверки

  messages:
    filter-enabled: "%prefix% &r&aФильтр чата включен!"
    filter-disabled: "%prefix% &r&eФильтр чата выключен!"
    no-permission: "%prefix% &r&cУ вас нет прав для использования этой команды!"
    contains-banned-word: "%prefix% &r&fПожалуйста, избегайте ненормативной лексики во время стрима &c&l♥"
    usage: "%prefix% &r&cИспользование: /chatfilter <on|off>"

banned-words:
  - "сука"
  - "блять"
  - "хуй"
  - "пизда"
  - "ебать"
  - "нахуй"
  - "пидор"
  - "бля"
  - "fuck"
  - "shit"
  - "dick"
  - "bitch"
  - "ass"
  - "whore"
  - "slut"
  - "bastard"
  - "nigger"
  - "nigga"
  - "naga"
  - "ниггер"
  - "нига"
  - "нага"
  - "пидорас"
  - "педик"
  - "гомик"
  - "петух"
  - "faggot"
  - "хиджаб"
  - "белый"
  - "натурал"
  - "гетеросексуал"
  - "хохол"
  - "хач"
  - "жид"
  - "москаль"
  - "ватник"
  - "сионист"
  - "куколд"
  - "конча"
  - "даун"
  - "аутист"
  - "дебил"
  - "retard"
  - "virgin"
  - "девственник"
  - "simp"
  - "симп"
  - "incel"
  - "инцел"
  - "cunt"
  - "вагина"
